[build]
  command = "npm run build"  # Команда для сборки проекта
  functions = "index.js"
  publish = "dist/"          # Папка, содержащая статические файлы после сборки

[dev]
  command = "npm run start"  # Команда для запуска сервера в режиме разработки